#!/usr/bin/env python3

import sys
import json

sys.path.append('/opt/yolov5')

import detect

with open('/opt/ml/input/data/config/params.json') as params_file:
    params = json.load(params_file)
    predict_params = params['predict']

opt = detect.parse_opt()
for p in predict_params:
    value = predict_params[p]
    if value:
        setattr(opt, p, value)

detect.main(opt)